apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    app: {{ .Chart.Name }}-server
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  selector:
    app: {{ .Chart.Name }}-client
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort